// <auto-generated />
using System;
using System.Collections.Generic;
using CtrlLove.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CtrlLove.Migrations
{
    [DbContext(typeof(CtrlLoveContext))]
    partial class CtrlLoveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChatRoomModelUserModel", b =>
                {
                    b.Property<Guid>("ChatRoomModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantsId")
                        .HasColumnType("uuid");

                    b.HasKey("ChatRoomModelId", "ParticipantsId");

                    b.HasIndex("ParticipantsId");

                    b.ToTable("ChatRoomModelUserModel");
                });

            modelBuilder.Entity("CtrlLove.Models.ChatRoomModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ChatRoomModels");
                });

            modelBuilder.Entity("CtrlLove.Models.InterestModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("CtrlLove.Models.LikeModel", b =>
                {
                    b.Property<Guid>("LikedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(1);

                    b.Property<Guid>("LikedUserId")
                        .HasColumnType("uuid")
                        .HasColumnOrder(2);

                    b.Property<bool>("Liked")
                        .HasColumnType("boolean");

                    b.HasKey("LikedByUserId", "LikedUserId");

                    b.HasIndex("LikedUserId");

                    b.ToTable("LikeModel");
                });

            modelBuilder.Entity("CtrlLove.Models.MessageModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ChatRoomModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("ChatRoomModelId");

                    b.HasIndex("SenderId");

                    b.ToTable("message");
                });

            modelBuilder.Entity("CtrlLove.Models.PhotoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("userId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("userId");

                    b.ToTable("photos");
                });

            modelBuilder.Entity("CtrlLove.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Biography")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int[]>("DesiredGenders")
                        .HasColumnType("integer[]");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int>("MaximumAge")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumAge")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Roles")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("InterestModelUserModel", b =>
                {
                    b.Property<Guid>("InterestsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserModelId")
                        .HasColumnType("uuid");

                    b.HasKey("InterestsId", "UserModelId");

                    b.HasIndex("UserModelId");

                    b.ToTable("InterestModelUserModel");
                });

            modelBuilder.Entity("ChatRoomModelUserModel", b =>
                {
                    b.HasOne("CtrlLove.Models.ChatRoomModel", null)
                        .WithMany()
                        .HasForeignKey("ChatRoomModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CtrlLove.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("ParticipantsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CtrlLove.Models.LikeModel", b =>
                {
                    b.HasOne("CtrlLove.Models.UserModel", "LikedByUser")
                        .WithMany("Likes")
                        .HasForeignKey("LikedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CtrlLove.Models.UserModel", "LikedUser")
                        .WithMany()
                        .HasForeignKey("LikedUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LikedByUser");

                    b.Navigation("LikedUser");
                });

            modelBuilder.Entity("CtrlLove.Models.MessageModel", b =>
                {
                    b.HasOne("CtrlLove.Models.ChatRoomModel", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatRoomModelId");

                    b.HasOne("CtrlLove.Models.UserModel", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("CtrlLove.Models.PhotoModel", b =>
                {
                    b.HasOne("CtrlLove.Models.UserModel", "user")
                        .WithMany("Photos")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("InterestModelUserModel", b =>
                {
                    b.HasOne("CtrlLove.Models.InterestModel", null)
                        .WithMany()
                        .HasForeignKey("InterestsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CtrlLove.Models.UserModel", null)
                        .WithMany()
                        .HasForeignKey("UserModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CtrlLove.Models.ChatRoomModel", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CtrlLove.Models.UserModel", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
